# Site settings
title: "Enzo Bergamo"
description: "Personal website"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Enzo Bergamo"
#resume_title:                   " "

# used for the contact button in _layouts/resume.html
resume_contact_email:           "ebergamo"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "936-223-4920"
resume_contact_address:         "Philadelphia, PA"

resume_header_contact_info:     ""
display_header_contact_info:    "true"

resume_header_intro: "<p> 
My name is Enzo Bergamo, and I am a first-year Ph.D. student in the <a href='https://oid.wharton.upenn.edu'>Operations, Information & Decisions</a> 
department at the <a href='https://www.wharton.upenn.edu'>Wharton School</a> of the University of Pennsylvania. I have received my 
Bachelor's and Master's Degree in Systems Science & Engineering at the <a href='https://www.seas.upenn.edu/'>University of 
Pennsylvania School of Engineering and Applied Science</a> where I was a <a href='https://global.upenn.edu/isss/penn-world-scholars'>Penn World Scholar</a>.

My interests lie in the areas of market design and the use of machine learning in the context of operations management and economics.
</p>

<p>
I have previously worked as a teaching assistant for Stochastic Systems Analysis and Simulation (ESE 3030) at the University of Pennsylvania. 
The lecture notes for the course can be found <a href='https://drive.google.com/file/d/1vzrLcG5CSmCEA3SUF7rSNsFp1HehhrsC/view?usp=sharing'>here</a>.
</p>" 

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank#resume_looking_for_work:        ""

# Decide which sections to use
# comment out to hide
# resume_section_experience:      false
# resume_section_education:       false
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_accomplishments: true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/EABergamo"
  #resume_facebook_url:          "https://www.facebook.com/maxim.shovkun"
  resume_linkedin_url:          "https://www.linkedin.com/in/eabergamo/"
  # resume_hackerrank_url:        "https://www.hackerrank.com/Rosenstein"
  # resume_medium_url:            "https://ebergamo.medium.com/"
  resume_pdf_url:            "https://drive.google.com/file/d/1ndGp7lTi4H8JKDdwbVJs1ojrw2Wq4wWs/view?usp=sharing"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

theme: jekyll-theme-cayman
