# Site settings
title: "Enzo Bergamo"
description: "Personal website"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Enzo Bergamo"
#resume_title:                   " "

# used for the contact button in _layouts/resume.html
resume_contact_email:           "ebergamo"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "936-223-4920"
resume_contact_address:         "Philadelphia, PA"

resume_header_contact_info:     ""
display_header_contact_info:    "true"

resume_header_intro: "<p> 
My name is Enzo Bergamo, and I am <a href='https://global.upenn.edu/isss/penn-world-scholars'>Penn World Scholar</a> currently
pursuing both a Bachelor's Degree and a Master's Degree in Systems Science & Engineering at the <a href='https://www.seas.upenn.edu/'>University of Pennsylvania School of Engineering 
and Applied Science</a>. I am originally from São Paulo, Brazil and I currently live in Philadelphia, Pennsylvania. My interests lie in areas such as machine learning, 
data visualization, optimization, as well as the application of these topics in different ways.
</p>" 

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank#resume_looking_for_work:        ""

# Decide which sections to use
# comment out to hide
# resume_section_experience:      false
# resume_section_education:       false
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_accomplishments: true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/EABergamo"
  #resume_facebook_url:          "https://www.facebook.com/maxim.shovkun"
  resume_linkedin_url:          "https://www.linkedin.com/in/eabergamo/"
  # resume_hackerrank_url:        "https://www.hackerrank.com/Rosenstein"
  resume_medium_url:            "https://ebergamo.medium.com/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

theme: jekyll-theme-cayman
