baseURL: "https://www.enzobergamo.com" 
title: Enzo A. Bergamo
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: CV
          url: 2024.12.28 Enzo Bergamo - CV.pdf
          weight: 2
        - name: Teaching
          url: courses/
          weight: 3

params:
    description: "Welcome to my website! I am a Ph.D. student in the Operations, Informations and Decisions department at the Wharton School of Business"
    author: Enzo A. Bergamo
    googleAnalyticsID: "G-K19E1W4Z12"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    favicon: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Enzo A. Bergamo
          subtitle: "<strong>Welcome to my website!</strong> I am a first-year Ph.D. student in the [<u>Operations, Information & Decisions</u>](https://oid.wharton.upenn.edu) 
          department at the [<u>Wharton School</u>](https://www.wharton.upenn.edu) of the University of Pennsylvania. 
          <br>  <br>
          I have received my  Bachelor's and Master's Degree in Systems Science & Engineering at the [<u>University of 
          Pennsylvania School of Engineering and Applied Science</u>](https://www.seas.upenn.edu) where I was a 
          [<u>Penn World Scholar</u>](https://global.upenn.edu/isss/penn-world-scholars).
          <br>  <br>    
          My research interests center around the use of machine learning techniques to understand and optimize decision-making in operations management problems."
          imageUrl: "profile_pic.jpg"
          imageTitle: Enzo Bergamo
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: CV
              url: cv.pdf
            - name: Teaching
              url: courses/

    # socialIcons:
    #     - name: CV
    #       url: cv.pdf
    #     - name: Email
    #       url: mailto:moritz.maria.von.igelfeld@gmail.com
    #     - name: Zoom
    #       url: https://www.zoom.us/my/igelfeld
    #     - name: Location
    #       url: location/
    #     - name: Office Hours
    #       url: officehours/
    #     - name: Google Scholar
    #       url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
    #     - name: GitHub
    #       url: https://github.com/pmichaillat
    #     - name: Substack
    #       url: https://pmichaillat.substack.com
    #     - name: YouTube
    #       url: https://www.youtube.com/@alexandermccallsmithoffici9000
    #     - name: Twitter
    #       url: https://twitter.com/McCallSmith

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Enzo A. Bergamo"
      icon: favicon.ico
      iconHeight: 24

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2